language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
before_install:
 - sudo add-apt-repository ppa:pmjdebruijn/stockfish-release -y
 - sudo apt-get update
 - sudo apt-get install -t trusty stockfish
install:
 - pip install coveralls
 - pip install spur
script:
 - coverage run --source chess test.py --verbose
 - coverage run --source chess --append -m doctest README.rst --verbose
 - coverage run --source chess --append perft.py
after_success:
 - coveralls
