language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
before_install:
 - wget https://stockfish.s3.amazonaws.com/stockfish-6-win.zip
 - unzip stockfish-6-win.zip
 - cp stockfish-6-win/Linux/stockfish_6_x64 /usr/games/stockfish
install:
 - pip install coveralls
 - pip install spur
script:
 - coverage run --source chess test.py --verbose
 - coverage run --source chess --append -m doctest README.rst --verbose
 - coverage run --source chess --append perft.py
after_success:
 - coveralls
