language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5.0b3"
before_install:
 - # Stockfish
 - wget https://stockfish.s3.amazonaws.com/stockfish-6-linux.zip
 - unzip stockfish-6-linux.zip
 - mkdir -p bin
 - cp stockfish-6-linux/Linux/stockfish_6_x64 bin/stockfish
 - export PATH="`pwd`/bin:${PATH}"
 - which stockfish || (echo $PATH && false)
 - # Gaviota tablebases
 - git clone https://github.com/michiguel/Gaviota-Tablebases.git --depth 1
 - cd Gaviota-Tablebases
 - make
 - export LD_LIBRARY_PATH="`pwd`:${LD_LIBRARY_PATH}"
 - cd ..
install:
 - python -c "import sys; sys.exit(int(sys.version_info < (3, 2)));" || pip install futures
 - pip install coveralls
 - pip install spur
script:
 - coverage run --source chess test.py --verbose
 - coverage run --source chess --append -m doctest README.rst --verbose
 - coverage run --source chess --append perft.py --verbose
after_success:
 - coveralls
